#!/usr/bin/env python3
"""
Utility functions for the visualization module.

This module provides common functions and utilities used across
different visualization components.
"""

import os
import json
import logging
import base64
import re
from typing import Dict, List, Any, Optional, Union
from pathlib import Path
import shutil
import tempfile

# Configure logging
logger = logging.getLogger(__name__)

class VisualizationUtils:
    """
    Utilities and helper functions for visualizations.
    """
    
    @staticmethod
    def generate_html_header(title: str, include_d3: bool = False, 
                           include_chartjs: bool = False,
                           include_custom_css: str = None) -> str:
        """
        Generate a standard HTML header with optional JavaScript libraries.
        
        Args:
            title: Title for the HTML page
            include_d3: Whether to include D3.js
            include_chartjs: Whether to include Chart.js
            include_custom_css: Optional custom CSS to include
            
        Returns:
            str: HTML header code
        """
        header = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f5f5f5;
            color: #333;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }}
        .header {{
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }}
        h1 {{
            margin: 0;
            color: #333;
            font-size: 24px;
        }}
        .section {{
            background-color: #fff;
            border-radius: 5px;
            padding: 20px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            margin-bottom: 30px;
        }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #7f8c8d;
            font-size: 14px;
        }}
"""
        
        # Add custom CSS if provided
        if include_custom_css:
            header += include_custom_css
        
        header += """
    </style>
"""
        
        # Include D3.js if requested
        if include_d3:
            header += """
    <script src="https://d3js.org/d3.v7.min.js"></script>
"""
        
        # Include Chart.js if requested
        if include_chartjs:
            header += """
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chartjs-plugin-datalabels/2.0.0/chartjs-plugin-datalabels.min.js"></script>
"""
        
        header += """
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{title}</h1>
        </div>
"""
        
        return header
    
    @staticmethod
    def generate_html_footer(include_attribution: bool = True) -> str:
        """
        Generate a standard HTML footer.
        
        Args:
            include_attribution: Whether to include AllSeeingEye attribution
            
        Returns:
            str: HTML footer code
        """
        footer = """
        <div class="footer">
"""
        
        if include_attribution:
            footer += """
            Generated by AllSeeingEye | Visualization Module
"""
        
        footer += """
        </div>
    </div>
</body>
</html>
"""
        
        return footer
    
    @staticmethod
    def create_output_bundle(output_file: str, 
                            additional_files: Optional[Dict[str, str]] = None,
                            bundle_js: bool = False) -> str:
        """
        Create a bundled HTML output with optional external resources.
        
        This function can either create a standalone HTML file with embedded 
        resources or create a directory with HTML and external resources.
        
        Args:
            output_file: Path to save the output
            additional_files: Optional dictionary of {filename: content}
            bundle_js: Whether to bundle JavaScript into the HTML or keep as separate files
            
        Returns:
            str: Path to the generated output
        """
        if not additional_files:
            return output_file
        
        # If output file has no extension or not .html, treat as directory
        if not os.path.splitext(output_file)[1] or not output_file.endswith('.html'):
            # Create directory if it doesn't exist
            os.makedirs(output_file, exist_ok=True)
            
            # Get main HTML file name
            main_html = os.path.join(output_file, 'index.html')
            
            # Write additional files
            for filename, content in additional_files.items():
                file_path = os.path.join(output_file, filename)
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
            
            return main_html
        else:
            # If we're bundling everything into the HTML file,
            # no additional files to write
            if bundle_js:
                return output_file
            
            # Create directory for the assets
            output_dir = os.path.splitext(output_file)[0] + '_files'
            os.makedirs(output_dir, exist_ok=True)
            
            # Write additional files
            for filename, content in additional_files.items():
                file_path = os.path.join(output_dir, filename)
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(content)
            
            return output_file
    
    @staticmethod
    def modify_html_content(html_content: str, additional_files: Dict[str, str], 
                         output_dir: str, bundle: bool = False) -> str:
        """
        Modify HTML content to either bundle resources or reference external files.
        
        Args:
            html_content: Original HTML content
            additional_files: Dictionary of {filename: content}
            output_dir: Directory where external files will be stored
            bundle: Whether to bundle resources into the HTML
            
        Returns:
            str: Modified HTML content
        """
        if not bundle:
            # If not bundling, simply return the original content
            return html_content
        
        # If bundling, replace external references with inline content
        modified_html = html_content
        
        # Replace script src references
        script_pattern = r'<script src="([^"]+)"></script>'
        for match in re.finditer(script_pattern, html_content):
            src = match.group(1)
            filename = os.path.basename(src)
            
            if filename in additional_files:
                script_content = additional_files[filename]
                inline_script = f'<script>{script_content}</script>'
                modified_html = modified_html.replace(match.group(0), inline_script)
        
        # Replace link href references for CSS
        css_pattern = r'<link rel="stylesheet" href="([^"]+)">'
        for match in re.finditer(css_pattern, html_content):
            href = match.group(1)
            filename = os.path.basename(href)
            
            if filename in additional_files:
                css_content = additional_files[filename]
                inline_css = f'<style>{css_content}</style>'
                modified_html = modified_html.replace(match.group(0), inline_css)
        
        return modified_html
    
    @staticmethod
    def embed_image(image_path: str, alt_text: str = "") -> str:
        """
        Embed an image file directly into HTML using base64 encoding.
        
        Args:
            image_path: Path to the image file
            alt_text: Alternative text for the image
            
        Returns:
            str: HTML img tag with embedded image
        """
        try:
            with open(image_path, 'rb') as image_file:
                encoded_image = base64.b64encode(image_file.read()).decode('utf-8')
            
            # Determine MIME type
            extension = os.path.splitext(image_path)[1].lower()
            mime_map = {
                '.png': 'image/png',
                '.jpg': 'image/jpeg',
                '.jpeg': 'image/jpeg',
                '.gif': 'image/gif',
                '.svg': 'image/svg+xml'
            }
            mime_type = mime_map.get(extension, 'image/png')
            
            # Create embedded image tag
            return f'<img src="data:{mime_type};base64,{encoded_image}" alt="{alt_text}">'
        
        except Exception as e:
            logger.error(f"Error embedding image {image_path}: {e}")
            return f'<img src="#" alt="Error loading image: {alt_text}">'
    
    @staticmethod
    def normalize_file_path(path: str) -> str:
        """
        Normalize a file path for consistent display.
        
        Args:
            path: File path to normalize
            
        Returns:
            str: Normalized path
        """
        # Replace backslashes with forward slashes
        path = path.replace('\\', '/')
        
        # Remove leading ./
        if path.startswith('./'):
            path = path[2:]
        
        return path
    
    @staticmethod
    def generate_color_scale(count: int, start_color: str = "#8dd3c7", end_color: str = "#bc80bd") -> List[str]:
        """
        Generate a color scale with the specified number of colors.
        
        Args:
            count: Number of colors to generate
            start_color: Starting color in hex format
            end_color: Ending color in hex format
            
        Returns:
            List[str]: List of hex color codes
        """
        def hex_to_rgb(hex_color):
            hex_color = hex_color.lstrip('#')
            return tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
        
        def rgb_to_hex(rgb):
            return '#{:02x}{:02x}{:02x}'.format(rgb[0], rgb[1], rgb[2])
        
        start_rgb = hex_to_rgb(start_color)
        end_rgb = hex_to_rgb(end_color)
        
        colors = []
        for i in range(count):
            t = i / (count - 1) if count > 1 else 0
            r = int(start_rgb[0] * (1 - t) + end_rgb[0] * t)
            g = int(start_rgb[1] * (1 - t) + end_rgb[1] * t)
            b = int(start_rgb[2] * (1 - t) + end_rgb[2] * t)
            colors.append(rgb_to_hex((r, g, b)))
        
        return colors
    
    @staticmethod
    def format_size(size_bytes: int) -> str:
        """
        Format file size in human-readable format.
        
        Args:
            size_bytes: Size in bytes
            
        Returns:
            str: Formatted size string (e.g., "1.23 MB")
        """
        if size_bytes == 0:
            return "0 B"
        
        units = ['B', 'KB', 'MB', 'GB', 'TB']
        i = 0
        
        while size_bytes >= 1024 and i < len(units) - 1:
            size_bytes /= 1024
            i += 1
        
        return f"{size_bytes:.2f} {units[i]}"
    
    @staticmethod
    def format_number(number: int) -> str:
        """
        Format a number with commas as thousands separators.
        
        Args:
            number: Number to format
            
        Returns:
            str: Formatted number string
        """
        return f"{number:,}"
    
    @staticmethod
    def copy_visualization_assets(output_path: str, assets_dir: Optional[str] = None) -> None:
        """
        Copy visualization assets to the output directory.
        
        Args:
            output_path: Path to the output directory
            assets_dir: Optional path to assets directory (defaults to module's assets)
        """
        if not assets_dir:
            # Use the module's assets directory
            module_dir = os.path.dirname(os.path.abspath(__file__))
            assets_dir = os.path.join(module_dir, 'assets')
        
        # If assets directory doesn't exist, return
        if not os.path.exists(assets_dir):
            logger.warning(f"Assets directory not found: {assets_dir}")
            return
        
        # Create output assets directory
        output_assets_dir = os.path.join(output_path, 'assets')
        os.makedirs(output_assets_dir, exist_ok=True)
        
        # Copy assets
        for item in os.listdir(assets_dir):
            src = os.path.join(assets_dir, item)
            dst = os.path.join(output_assets_dir, item)
            
            if os.path.isfile(src):
                shutil.copy2(src, dst)
            elif os.path.isdir(src):
                if os.path.exists(dst):
                    shutil.rmtree(dst)
                shutil.copytree(src, dst)


class VisualizationTemplateManager:
    """
    Manages templates for visualizations.
    """
    
    def __init__(self, template_dir: Optional[str] = None):
        """
        Initialize with template directory.
        
        Args:
            template_dir: Directory containing templates (defaults to module's template directory)
        """
        if template_dir:
            self.template_dir = template_dir
        else:
            # Use the module's template directory
            module_dir = os.path.dirname(os.path.abspath(__file__))
            self.template_dir = os.path.join(module_dir, 'templates')
        
        # Create template directory if it doesn't exist
        os.makedirs(self.template_dir, exist_ok=True)
    
    def get_template(self, template_name: str) -> str:
        """
        Get a template file content.
        
        Args:
            template_name: Name of the template
            
        Returns:
            str: Template content
        """
        template_path = os.path.join(self.template_dir, template_name)
        
        try:
            with open(template_path, 'r', encoding='utf-8') as f:
                return f.read()
        except FileNotFoundError:
            logger.warning(f"Template not found: {template_name}")
            return ""
    
    def render_template(self, template_name: str, context: Dict[str, Any]) -> str:
        """
        Render a template with the provided context.
        
        Args:
            template_name: Name of the template
            context: Dictionary of variables to use in the template
            
        Returns:
            str: Rendered template
        """
        template = self.get_template(template_name)
        
        # Simple template rendering with string formatting
        for key, value in context.items():
            placeholder = f"{{{{{key}}}}}"
            template = template.replace(placeholder, str(value))
        
        return template
    
    def save_template(self, template_name: str, content: str) -> None:
        """
        Save a template to the template directory.
        
        Args:
            template_name: Name of the template
            content: Template content
        """
        template_path = os.path.join(self.template_dir, template_name)
        
        try:
            with open(template_path, 'w', encoding='utf-8') as f:
                f.write(content)
            logger.info(f"Template saved: {template_name}")
        except Exception as e:
            logger.error(f"Error saving template {template_name}: {e}")
    
    def list_templates(self) -> List[str]:
        """
        List all available templates.
        
        Returns:
            List[str]: List of template names
        """
        try:
            return [f for f in os.listdir(self.template_dir) 
                   if os.path.isfile(os.path.join(self.template_dir, f))]
        except Exception as e:
            logger.error(f"Error listing templates: {e}")
            return []


def convert_data_to_json(data: Any) -> str:
    """
    Convert data to JSON string, with special handling for complex objects.
    
    Args:
        data: Data to convert
        
    Returns:
        str: JSON string
    """
    class ComplexEncoder(json.JSONEncoder):
        def default(self, obj):
            if isinstance(obj, set):
                return list(obj)
            if isinstance(obj, Path):
                return str(obj)
            return super().default(obj)
    
    return json.dumps(data, cls=ComplexEncoder)


def create_temporary_file(content: str, suffix: str = '.html') -> str:
    """
    Create a temporary file with the given content.
    
    Args:
        content: Content to write to the file
        suffix: File extension
        
    Returns:
        str: Path to the temporary file
    """
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=False, mode='w', encoding='utf-8') as temp_file:
        temp_file.write(content)
        return temp_file.name
